### ISSUE TITLE
Firebase Realtime Database How to use?

### ISSUE THREAD

**Issue by ahmetozalp** [kriasoft/react-firebase-starter#236]
Hi An example for real-time database use?

**Comment by ahmetozalp** [comment]
help me?

**Comment by scharinger** [comment]
Hi! I'm also looking into how the db works in this project. But as far as I can read from the readme.md it does not use the Firebase real-time database but a "[Cloud SQL](https://cloud.google.com/sql/docs/)" which is something else. I think the communication to the SQL Server goes like this, client code -> relayjs -> GraphQL. I would like to know more about the details myself.

**Comment by robertoaikode** [comment]
Did they connect with RTD or Firestore?
