### ISSUE TITLE
Add user picture to the Toolbar component

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-firebase-starter#272]
![image](https://user-images.githubusercontent.com/197134/34109736-8ed0d240-e415-11e7-98e8-4cd8e7c53a17.png)

- [ ] Add user picture into the `src/App/Toolbar` component (HINT: use `this.props.user.photoURL`)
- [ ] Add a drop-down menu with `[My Account]` and `[Sign Out]` buttons

**See**

https://material-ui-next.com/demos/app-bar/
https://material-ui-next.com/demos/avatars/
https://material-ui-next.com/demos/menus/

**Comment by Nateeo** [comment]
Hi @koistya, I'd be happy to pick this up :)
