### ISSUE TITLE
Monkeypatching source code of other packages is fragile

### ISSUE THREAD

**Issue by gaearon** [kriasoft/react-firebase-starter#278]
As a maintainer of `babel-preset-react-app` I am not very happy about these lines:

https://github.com/kriasoft/react-firebase-starter/blob/b917ae43b212bdb6a53422ce4760f870f813482e/setup.js#L32-L64

This is incredibly fragile, and is doing a disservice to all the people using this starter kit when we break this in the future.

It is quite possible that your users will be left with no good upgrade path. It is also very likely they are not experienced enough to figure out an alternative solution to this hack. In my opinion it’s irresponsible to rely on something like this without a clear disclaimer in the README that the project is built on a fragile foundation and can break with patch updates of the underlying tools.

I don’t have a great solution to this. Perhaps you could fork `react-scripts` or at least `babel-preset-react-app`? Even using Yarn `resolutions` to point to a fork would be less fragile than trying to monkeypatch the source depending on a variable name.

Thanks for consideration!

**Comment by ermik** [comment]
As the aforementioned "beginner", I am quite perplexed after understanding how flaky this workaround is. If not for @gaearon's feedback in the CRA repo it is very likely that I would've ended up using this kit to enable relay in one of the projects.

This also concerns this [answer on StackOverflow](https://stackoverflow.com/questions/40729657/whats-the-easiest-way-to-use-create-react-app-with-relay) which should at the very slightest bear an identical disclaimer. 

Please clarify this across the board.

**Comment by koistya** [comment]
This is no longer relevant after migrating to [React App SDK](https://github.com/kriasoft/react-app) (#280).
