### ISSUE TITLE
Possible to use environment variables?

### ISSUE THREAD

**Issue by AndroidDoctorr** [kriasoft/react-firebase-starter#279]
Is it possible to use environment variables in this project, like via a .env file in the root folder?

**Comment by koistya** [comment]
In case with Firebase, you add environment variables by using Firebase CLI:

```
$ firebase functions:config:set db.password="<secret>"
```

And then reference that variable in your server-side code like this:

```
import { config } from 'firebase-functions';

const password = config().database.password;
```

If you need environment variables for client-side portion of the app, you can pass them using `REACT_APP_` prefix, see Create React App docs [here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables).

**Comment by JamieCorkhill** [comment]
@koistya How can I use environment variables with Firebase Hosting client-side if I'm using my own boilerplate and not Create React App?

Thanks.
