### ISSUE TITLE
Problems with environment variables when deploying Firebase functions

### ISSUE THREAD

**Issue by PabloMarch** [kriasoft/react-firebase-starter#310]
Hello there! I'm updating this issue with the real problem, when I try to deploy the project in Firebase I'm getting an error with all node environment vars `process.env`, it makes sense because the functions has its own environment but this is causing the deploy to break, firebase logs attached.

![screenshot from 2018-05-27 20-28-37](https://user-images.githubusercontent.com/741933/40593714-efaecccc-61ef-11e8-89f6-1a7370952024.png)
![screenshot from 2018-05-27 20-49-55](https://user-images.githubusercontent.com/741933/40593715-efc8bace-61ef-11e8-9462-b0d0e9afa3bd.png)

Note: I also tried updating node to `v.6.11.5` but same happens. Any update I'll be posting. Thanks!

**Comment by PabloMarch** [comment]
At this point I've got almost all the project running but I still don't get what is causing compilation problems on the build/app.js file. This is code I've transplanted code in my project functions config, should I continue adding each node env var here?:

```
{
  "key": FIREBASE_SERVICE_KEY,
  "api": {
    "browserkey": "FIREBASE_API_SERVER_KEY"
  },
  "facebook": {
    "app_secret": "FACEBOOK_APP_SECRET",
    "app_id": "FACEBOOK_APP_ID"

  },
  "google": {
    "client_secret": "GOOGLE_CLIENT_SECRET",
    "client_id": "GOOGLE_CLIENT_ID",
    "cloud_id": "GCP_PROJECT"
  },
  "auth": {
    "domain": "FIREBASE_PROJECT_ID.firebaseapp.com"
  },
  "jwt": {
    "secret": "JWT_SECRET"
  }
}
```

I also tried excluding the env vars in `firebase.json` as this but it fails:

```
{
  "functions": {
  "source": ".",
    "ignore": [
      ".!(env)"
      ...
  }
}
```

**Comment by rstickel** [comment]
I’m experiencing the same issue. Any resolutions?

**Comment by andrewkslv** [comment]
Hey @rstickel @PabloMarch 
Your error stack says that you don't have property `app.origin` in your firebase config `firebase functions:config:set app.origin="your-domain-name"`

**Comment by koistya** [comment]
@PabloMarch @rstickel @andrewkslv I just removed the usage of Firebase's `config()` function in favor of having API keys, secrets etc. stored in one place - `.env/.env.production` files. This way it must be easier to deploy the app.

On the `master` branch you may have all the environment variables set for a test/staging deployment, and for production deployment, you would create a separate secure branch containing config overrides.
