### ISSUE TITLE
build/index.html shows blank page after build

### ISSUE THREAD

**Issue by khanna2005m** [kriasoft/react-firebase-starter#317]
Hi,

I just start using react and it works fine, but. My problem is that when I run 'npm run build' everything works fine until I go to the **'build/index.html'** that shows a **blank page** in my browser.

**Comment by koistya** [comment]
`npm run build` (or, `yarn build`) is only supposed to be used right before deployment, when you need to compile everything into a distributable "package" that can be uploaded to a server. In order to run website locally you need to run `npm start` (or, `yarn start`).
