### ISSUE TITLE
Replace `classnames` npm module with `clsx`

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-firebase-starter#332]
https://github.com/lukeed/clsx

Ref https://github.com/mui-org/material-ui/pull/14152

**Comment by frenzzy** [comment]
[Classcat](https://github.com/jorgebucaran/classcat) is the fastest alternative to both [classnames](https://github.com/JedWatson/classnames) and [clsx](https://github.com/lukeed/clsx), JFYI

**Comment by koistya** [comment]
Fixed in #334
