### ISSUE TITLE
error app@0.0.0: The engine "node" is incompatible with this module. Expected version "10". Got "12.13.0"

### ISSUE THREAD

**Issue by chaitu210493** [kriasoft/react-firebase-starter#441]
I am trying to use this I getting following issue on my cmd line
error app@0.0.0: The engine "node" is incompatible with this module. Expected version "10". Got "12.13.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

How to fix this !!. I have been trying to fix this for a while now

**Comment by chaitu210493** [comment]
Change the version from 12 to 10 in Package.JSON

**Comment by thehappydinoa** [comment]
This did not work for me, it only worked when I changed it to my version `12.12.0`
