### ISSUE TITLE
Build with distinct environment variables?

### ISSUE THREAD

**Issue by dsernst** [kriasoft/react-firebase-starter#51]
Is there a way to build with environment specific variables?

e.g. I have a setting `API_URL` in `config.js`, and I want that value to change between local development, stage builds, and production builds without exposing the stage `API_URL` to the production build.

Trying something like `process.env` doesn't seem to be working. It only compiles into an empty object `{}`.

**Comment by dsernst** [comment]
@koistya Do you have any ideas?

**Comment by dsernst** [comment]
Maybe this would work: https://www.npmjs.com/package/inline-environment-variables-webpack-plugin

**Comment by koistya** [comment]
How about accessing it via `process.env.API_URL` in your code and use Webpack's [DefinePlugin](https://github.com/webpack/docs/wiki/list-of-plugins#defineplugin) to embed a correct value based on the build type into your bundles. Also look into [tree-shaking](http://www.2ality.com/2015/12/webpack-tree-shaking.html) feature in Webpack 2.0.

**Comment by dsernst** [comment]
Very cool, this looks perfect.

**Comment by koistya** [comment]
The latest version of the boilerplate is using Create React App, so you can use it's convention to inject environment variables into the app bundle(s):

```bash
REACT_APP_API=https://graphql-demo.kriasoft.com yarn build
```
